# Generated by Django 3.1.4 on 2021-01-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210121_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=True, verbose_name='является ли главой организации crm'),
        ),
    ]
