# Generated by Django 3.1.6 on 2021-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210203_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='user/avatar/', verbose_name='аватар профиля'),
        ),
    ]
