# Generated by Django 3.1.7 on 2021-03-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210209_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='краткая биография'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время первого входа'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('GM', 'Мужской'), ('GF', 'Женский')], default='GENDER_MALE', max_length=2, verbose_name='ваш пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка на github'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatar/', verbose_name='аватар профиля'),
        ),
    ]
