# Generated by Django 3.1.7 on 2021-03-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0008_auto_20210317_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hard_skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='base.HardSkill'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='base.city', verbose_name='город'),
        ),
        migrations.AddField(
            model_name='user',
            name='soft_skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='base.SoftSkill'),
        ),
    ]
