# Generated by Django 3.1.7 on 2021-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0009_auto_20210317_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hard_skill',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.HardSkill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='soft_skill',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.SoftSkill'),
        ),
    ]
