# Generated by Django 3.1.7 on 2021-04-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0010_auto_20210323_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='base.city', verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='рассылка вакансий по email'),
        ),
    ]
