version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  db:
    image: postgres:11
    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

volumes:
  portfolio_postgres_data: