version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/src
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:11
    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  portfolio_postgres_data: