version: "3.9"

services:
  web:
    build: ./
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    env_file:
      - ./.env
    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  portfolio_postgres_data:
