# Generated by Django 3.1.5 on 2021-01-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
