# Generated by Django 3.1.4 on 2021-01-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='является ли агентом crm'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=False, verbose_name='является ли главой организации crm'),
        ),
    ]
