# Generated by Django 3.1.6 on 2021-02-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
        ('accounts', '0005_auto_20210129_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='рассылка вакансий по email'),
        ),
    ]
