# Generated by Django 3.1.4 on 2021-01-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210120_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
