# Generated by Django 3.1.4 on 2021-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('STATUS_NEW', 'Новый'), ('STATUS_CONTACTED', 'Связались'), ('STATUS_CONTACTED', 'Согласен'), ('STATUS_UNCONVERTED', 'Отказано')], default='STATUS_NEW', max_length=30, verbose_name='статус'),
        ),
    ]
