# Generated by Django 3.1.4 on 2021-01-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
